[package]
name = "toby-fs"
description = "The per-machine virtio-fs back end."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fuse-backend-rs.workspace = true
libc.workspace = true
nix.workspace = true
toby-vfs.workspace = true
vhost.workspace = true
vhost-user-backend.workspace = true
virtio-bindings.workspace = true
virtio-queue.workspace = true
vm-memory.workspace = true
vmm-sys-util.workspace = true

[lints]
workspace = true
