FROM archlinux:base-devel

RUN pacman -Syu --noconfirm \
    bash \
    ca-certificates \
    curl \
    git \
    github-cli \
    gnupg \
    gzip \
    jq \
    make \
    musl \
    nodejs \
    npm \
    openssh \
    python \
    qemu-img \
    rustup \
    tar \
    unzip \
    xdg-utils \
    zstd \
    && pacman -Scc --noconfirm
