// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/control/tunnel/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_internal_control_tunnel_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_tunnel_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_tunnel_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ReadyRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_internal_control_tunnel_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_tunnel_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_tunnel_tunnel_proto_rawDescGZIP(), []int{1}
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Close         bool                   `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_internal_control_tunnel_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_tunnel_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_internal_control_tunnel_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

var File_internal_control_tunnel_tunnel_proto protoreflect.FileDescriptor

const file_internal_control_tunnel_tunnel_proto_rawDesc = "" +
	"\n" +
	"$internal/control/tunnel/tunnel.proto\x12\x0etoby.tunnel.v1\"\"\n" +
	"\fReadyRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\x0f\n" +
	"\rReadyResponse\"1\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05close\x18\x02 \x01(\bR\x05close2\xc8\x01\n" +
	"\x06Tunnel\x12D\n" +
	"\x05Ready\x12\x1c.toby.tunnel.v1.ReadyRequest\x1a\x1d.toby.tunnel.v1.ReadyResponse\x12;\n" +
	"\aConnect\x12\x15.toby.tunnel.v1.Chunk\x1a\x15.toby.tunnel.v1.Chunk(\x010\x01\x12;\n" +
	"\aControl\x12\x15.toby.tunnel.v1.Chunk\x1a\x15.toby.tunnel.v1.Chunk(\x010\x01B)Z'petris.dev/toby/internal/control/tunnelb\x06proto3"

var (
	file_internal_control_tunnel_tunnel_proto_rawDescOnce sync.Once
	file_internal_control_tunnel_tunnel_proto_rawDescData []byte
)

func file_internal_control_tunnel_tunnel_proto_rawDescGZIP() []byte {
	file_internal_control_tunnel_tunnel_proto_rawDescOnce.Do(func() {
		file_internal_control_tunnel_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_tunnel_tunnel_proto_rawDesc), len(file_internal_control_tunnel_tunnel_proto_rawDesc)))
	})
	return file_internal_control_tunnel_tunnel_proto_rawDescData
}

var file_internal_control_tunnel_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_control_tunnel_tunnel_proto_goTypes = []any{
	(*ReadyRequest)(nil),  // 0: toby.tunnel.v1.ReadyRequest
	(*ReadyResponse)(nil), // 1: toby.tunnel.v1.ReadyResponse
	(*Chunk)(nil),         // 2: toby.tunnel.v1.Chunk
}
var file_internal_control_tunnel_tunnel_proto_depIdxs = []int32{
	0, // 0: toby.tunnel.v1.Tunnel.Ready:input_type -> toby.tunnel.v1.ReadyRequest
	2, // 1: toby.tunnel.v1.Tunnel.Connect:input_type -> toby.tunnel.v1.Chunk
	2, // 2: toby.tunnel.v1.Tunnel.Control:input_type -> toby.tunnel.v1.Chunk
	1, // 3: toby.tunnel.v1.Tunnel.Ready:output_type -> toby.tunnel.v1.ReadyResponse
	2, // 4: toby.tunnel.v1.Tunnel.Connect:output_type -> toby.tunnel.v1.Chunk
	2, // 5: toby.tunnel.v1.Tunnel.Control:output_type -> toby.tunnel.v1.Chunk
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_control_tunnel_tunnel_proto_init() }
func file_internal_control_tunnel_tunnel_proto_init() {
	if File_internal_control_tunnel_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_tunnel_tunnel_proto_rawDesc), len(file_internal_control_tunnel_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_control_tunnel_tunnel_proto_goTypes,
		DependencyIndexes: file_internal_control_tunnel_tunnel_proto_depIdxs,
		MessageInfos:      file_internal_control_tunnel_tunnel_proto_msgTypes,
	}.Build()
	File_internal_control_tunnel_tunnel_proto = out.File
	file_internal_control_tunnel_tunnel_proto_goTypes = nil
	file_internal_control_tunnel_tunnel_proto_depIdxs = nil
}
