# Toby's default image: used when no image is configured and to boot
# builder machines.

[Distribution]
Distribution=debian
Release=trixie
Repositories=main

[Output]
Format=directory

[Content]
Bootable=no
Packages=
        apt
        bash
        ca-certificates
        curl
        dbus
        dracut
        git
        iproute2
        jq
        less
        make
        nodejs
        openssh-client
        procps
        python3
        sudo
        systemd
        systemd-sysv
        tar
        unzip
        vim-tiny
        zstd
        bubblewrap
        buildah
        cpio
        debian-archive-keyring
        dracut-core
        e2fsprogs
        fuse-overlayfs
        podman
        python3-pefile
        systemd-container
        uidmap
