[package]
name = "toby"
description = "Runs development tools inside KVM virtual machines."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "toby"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mimalloc.workspace = true
tokio.workspace = true
toby-guest.workspace = true

[dev-dependencies]
libc.workspace = true
nix.workspace = true
tempfile.workspace = true
toby-proto.workspace = true

[lints]
workspace = true
