[package]
name = "toby"
description = "Runs development tools inside KVM virtual machines."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "toby"
path = "src/main.rs"

[dependencies]
futures-util.workspace = true
anyhow.workspace = true
clap.workspace = true
http-body-util.workspace = true
hyper-util.workspace = true
hyper.workspace = true
libc.workspace = true
mimalloc.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
toby-api.workspace = true
toby-config.workspace = true
toby-daemon.workspace = true
toby-engine.workspace = true
toby-fs.workspace = true
toby-guest.workspace = true
toby-machine.workspace = true
toby-proxy.workspace = true
toby-proto.workspace = true
toby-store.workspace = true
toby-svc.workspace = true
toby-term.workspace = true
toby-tools.workspace = true
toby-vfs.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
