[package]
name = "toby-proxy"
description = "The models and remote MCP proxy."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
http-body-util.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
hyper.workspace = true
nix.workspace = true
toby-config.workspace = true
toby-proto.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
