[package]
name = "toby-daemon"
description = "tobyd, the per-user control plane."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
utoipa.workspace = true
axum.workspace = true
futures-util.workspace = true
toby-machine.workspace = true
bytes.workspace = true
http-body.workspace = true
hyper-util.workspace = true
hyper.workspace = true
libc.workspace = true
minijinja.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
toby-api.workspace = true
toby-config.workspace = true
toby-guest.workspace = true
toby-proto.workspace = true
toby-proxy.workspace = true
toby-store.workspace = true
toby-svc.workspace = true
toby-tools.workspace = true
tokio.workspace = true
toml.workspace = true
tower.workspace = true
ureq.workspace = true

[lints]
workspace = true
