[package]
name = "toby-api"
description = "Types of the tobyd HTTP API."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
utoipa.workspace = true
serde.workspace = true
toby-proto.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
